/**
 * Prototype access control (docs/prototypes-plan.md, Phase 1).
 *
 * Two primitives, both WebCrypto-only (Pages Functions runtime):
 *
 * 1. PBKDF2-HMAC-SHA-256 password records, stored in the manifest as
 *    `pbkdf2$<iterations>$<salt-b64u>$<hash-b64u>` and generated by
 *    scripts/prototype-password.mjs — plaintext never enters the repo.
 *
 * 2. HMAC-SHA256 signed access cookies. A successful password (or, later,
 *    magic-link) grants a cookie scoped to Path=/p/<stack>/ carrying the
 *    stack's tokenVersion and an expiry; bumping tokenVersion in the
 *    manifest revokes every outstanding cookie for that stack. The signing
 *    secret comes from the PROTOTYPES_AUTH_SECRET environment variable
 *    (dashboard-managed; .dev.vars locally), never from the repo.
 *
 * Cookie format: jh_proto_<stack> = base64url("v<tokenVersion>.<expMs>").<sig>
 * where sig = base64url(HMAC-SHA256(secret, "<stack>.<payload>")).
 */

const PBKDF2_ITERATIONS = 100_000
const COOKIE_TTL_MS = 14 * 24 * 60 * 60 * 1000 // 14 days

// --- base64url helpers --------------------------------------------------------

function bytesToB64u(bytes: ArrayBuffer | Uint8Array): string {
  const view = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes)
  let binary = ''
  for (const byte of view) binary += String.fromCharCode(byte)
  return btoa(binary).replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '')
}

function b64uToBytes(value: string): Uint8Array {
  const b64 = value.replace(/-/g, '+').replace(/_/g, '/')
  const binary = atob(b64)
  const bytes = new Uint8Array(binary.length)
  for (let i = 0; i < binary.length; i += 1) bytes[i] = binary.charCodeAt(i)
  return bytes
}

function timingSafeEqual(a: Uint8Array, b: Uint8Array): boolean {
  if (a.length !== b.length) return false
  let diff = 0
  for (let i = 0; i < a.length; i += 1) diff |= a[i] ^ b[i]
  return diff === 0
}

// --- PBKDF2 password records ----------------------------------------------------

/** Verify a plaintext password against a manifest `pbkdf2$…` record. */
export async function verifyPrototypePassword(
  password: string,
  record: string,
): Promise<boolean> {
  const parts = record.split('$')
  if (parts.length !== 4 || parts[0] !== 'pbkdf2') return false
  const iterations = Number(parts[1])
  if (!Number.isInteger(iterations) || iterations <= 0) return false
  const salt = b64uToBytes(parts[2])
  const expected = b64uToBytes(parts[3])
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(password),
    'PBKDF2',
    false,
    ['deriveBits'],
  )
  const derived = await crypto.subtle.deriveBits(
    { name: 'PBKDF2', hash: 'SHA-256', salt, iterations },
    key,
    expected.length * 8,
  )
  return timingSafeEqual(new Uint8Array(derived), expected)
}

// --- Signed access cookies ------------------------------------------------------

export function prototypeCookieName(stackSlug: string): string {
  return `jh_proto_${stackSlug.replace(/-/g, '_')}`
}

async function signPayload(secret: string, message: string): Promise<string> {
  const key = await crypto.subtle.importKey(
    'raw',
    new TextEncoder().encode(secret),
    { name: 'HMAC', hash: 'SHA-256' },
    false,
    ['sign'],
  )
  const signature = await crypto.subtle.sign('HMAC', key, new TextEncoder().encode(message))
  return bytesToB64u(signature)
}

/** Build the Set-Cookie value granting access to a stack (post-unlock). */
export async function issuePrototypeCookie(
  stackSlug: string,
  tokenVersion: number,
  secret: string,
  nowMs: number,
): Promise<string> {
  const payload = `v${tokenVersion}.${nowMs + COOKIE_TTL_MS}`
  const signature = await signPayload(secret, `${stackSlug}.${payload}`)
  return (
    `${prototypeCookieName(stackSlug)}=${bytesToB64u(new TextEncoder().encode(payload))}.${signature}; ` +
    `Path=/p/${stackSlug}/; HttpOnly; Secure; SameSite=Lax; Max-Age=${Math.floor(COOKIE_TTL_MS / 1000)}`
  )
}

/**
 * Check a request's Cookie header for a valid grant: correct stack,
 * well-formed payload, valid signature, unexpired, and matching the
 * manifest's current tokenVersion. Any anomaly fails closed.
 */
export async function hasPrototypeAccess(
  request: Request,
  stackSlug: string,
  tokenVersion: number,
  secret: string,
  nowMs: number,
): Promise<boolean> {
  const header = request.headers.get('Cookie') ?? ''
  const prefix = `${prototypeCookieName(stackSlug)}=`
  const raw = header
    .split(';')
    .map((part) => part.trim())
    .find((part) => part.startsWith(prefix))
  if (!raw) return false
  const value = raw.slice(prefix.length)
  const dot = value.lastIndexOf('.')
  if (dot <= 0) return false
  const payloadB64 = value.slice(0, dot)
  const signature = value.slice(dot + 1)
  let payload: string
  try {
    payload = new TextDecoder().decode(b64uToBytes(payloadB64))
  } catch {
    return false
  }
  const match = payload.match(/^v(\d+)\.(\d+)$/)
  if (!match) return false
  if (Number(match[1]) !== tokenVersion) return false
  if (Number(match[2]) <= nowMs) return false
  const expected = await signPayload(secret, `${stackSlug}.${payload}`)
  return timingSafeEqual(
    new TextEncoder().encode(signature),
    new TextEncoder().encode(expected),
  )
}
